name: Docker Hub Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Rust build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/rust/1.58-tencentyun
          push: true
          tags: redsos/rust:1.58-tencentyun
      -
        name: Python build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/python/3.9-tencentyun
          push: true
          tags: redsos/python:3.9-tencentyun
      -
        name: Node build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/node/16-tencentyun
          push: true
          tags: redsos/node:16-tencentyun
          
