name: github ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (Rust)
        uses: docker/build-push-action@v2
        with:
          context: ./rust/1.58-tencentyun
          push: true
          tags: redsos/rust:1.58-tencentyun
      -
        name: Build and push (Python)
        uses: docker/build-push-action@v2
        with:
          context: ./python/3.9-tencentyun
          push: true
          tags: redsos/python:3.9-tencentyun
      -
        name: Build and push (Node)
        uses: docker/build-push-action@v2
        with:
          context: ./node/16-tencentyun
          push: true
          tags: redsos/node:16-tencentyun
          
